# Generated by Django 4.1.2 on 2022-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_sites',
            name='url_class',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search_sites',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='search_sites',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
